### PR TITLE
fix: Make port_wrapper.sh executable during installation

### LINKED ISSUE #15: Lexical won't start because the port_wrapper script isn't executable
VSCode isn't able to start an auto-installed version of lexical since the addition of the `port_wrapper.sh` script in remote control because it is not executable after zip extraction. We need to to make this script executable in the installation process.

Of not is that the path to this script contains the version number that lexical was compiled with, so we'll probably need a bit of logic to find the remote_control directory regardless of the version number.

### PR DESCRIPTION
**Pull request by Blond11516**
Fixes #15

### CODE REVIEW

**Review by scottming — APPROVED** [review]

File: src/language-server.ts [hunk 1]
```diff
@@ -191,6 +191,21 @@ namespace LanguageServer {
...
+
+		if (remoteControlDirectoryName !== undefined) {
+			const portWrapperUri = Uri.joinPath(
+				releaseUri,
+				"lib",
+				remoteControlDirectoryName,
+				"priv",
+				"port_wrapper.sh"
+			);
+			fs.chmodSync(portWrapperUri.fsPath, 0o755);
```
Comment (scottming) [inline src/language-server.ts:207]: interesting, after downloading, the the prot_wrapper.sh is not a executable sh.

Comment (Blond11516) [reply src/language-server.ts:207]: Yeah none of the files that should be executable are. Don't know why that is. It's definitely not a zip thing, maybe github makes them non-executable for security reasons or something 🤷
